<Project Sdk="Godot.NET.Sdk/4.4.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>Forge</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="0.17.0" />
  </ItemGroup>
</Project>
